/*
 * File: app/view/ContentPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.ContentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contentpanel',

    requires: [
        'SD.view.ContentPanelViewModel',
        'SD.view.ContentPanelViewController',
        'Ext.plugin.Responsive'
    ],

    config: {
        dockedItems: {
            xtype: 'toolbar',
            dock: 'top',
            itemid: 'contentPanel',
            layout: 'auto',
            items: [
                {
                    xtype: 'breadcrumb',
                    id: 'breadcrumb',
                    flex: 1,
                    itemId: 'breadcrumb',
                    publishes: 'selection',
                    bind: {
                        store: '{MenuStore}'
                    },
                    plugins: 'responsive',
                    responsiveConfig: {
                        'width >= 800': {
                            visible: false
                        },
                        'width < 800': {
                            visible: true
                        }
                    }
                },
                {
                    xtype: 'panel',
                    itemId: 'contentPanel',
                    title: 'Content',
                    bind: {
                        title: '{breadcrumb.selection.text}'
                    },
                    flex: '1',
                    tools: [
                        {
                            xtype: 'tool',
                            tooltip: 'Reduce font size',
                            type: 'minus',
                            handler: function() {
                                        this.up('#contentPanel1').getController().handleFontSizeAction('-1')
                                    }
                        },
                        {
                            xtype: 'tool',
                            tooltip: 'Increase font size',
                            type: 'plus',
                            handler: function() {
                                    this.up('#contentPanel1').getController().handleFontSizeAction('1') 
                                }
                        },
                        {
                            xtype: 'tool',
                            callback: function(owner, tool, event) {
                                var doc = window.document;
                                var docEl = doc.documentElement;
                        
                        var requestFullScreen = docEl.requestFullscreen || docEl.mozRequestFullScreen || docEl.webkitRequestFullScreen || docEl.msRequestFullscreen;
                        var cancelFullScreen = doc.exitFullscreen || doc.mozCancelFullScreen || doc.webkitExitFullscreen || doc.msExitFullscreen;
                        
                        if(!doc.fullscreenElement && !doc.mozFullScreenElement && !doc.webkitFullscreenElement && !doc.msFullscreenElement) {
                        requestFullScreen.call(docEl);
                        }
                        else {
                        cancelFullScreen.call(doc);
                        }
                        
                        },
                            itemId: 'fullScreenId',
                            hidden: true,
                            tooltip: 'Play the slideshow from the selected slide',
                            type: 'maximize'
                        }
                    ]
                }
            ]
        }
    },

    controller: 'contentpanel',
    viewModel: {
        type: 'contentpanel'
    },
    id: 'content-pnl',
    itemId: 'contentPanel1',
    scrollable: true,
    layout: 'fit',
    bodyPadding: 11

});