/*
 * File: app/view/ContentPanelViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.ContentPanelViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.contentpanel',

    requires: [
        'SD.view.util.Contstant'
    ],

    handleFontSizeAction: function(value) {
        var headerPage = Ext.get(this.view.body.dom).down('.slide');  //-- Header
        var articlePage = Ext.get(this.view.body.dom).down('.markdown-body');  //-- Article

        var currentHeaderFontSize = headerPage.getStyle('font-size');
        var currentArticleFontSize = articlePage.getStyle('font-size');

        updatedHeaderFontSize = parseInt(currentHeaderFontSize) + (SD.view.util.Contstant.updationValue*value)  + "px";
        updatedArticleFontSize = parseInt(currentArticleFontSize) +(SD.view.util.Contstant.updationValue*value) + "px";
        if(value =='-1'){
           if(parseInt(updatedHeaderFontSize) >(parseInt(SD.view.util.Contstant.headerFontSize)-1)){
            headerPage.setStyle('font-size',updatedHeaderFontSize);
           }else{
           headerPage.setStyle('font-size',SD.view.util.Contstant.headerFontSize);
           }
           if(parseInt(updatedArticleFontSize) >(parseInt(SD.view.util.Contstant.articleFontSize)-1)){
            articlePage.setStyle('font-size',updatedArticleFontSize);
           }else{
                articlePage.setStyle('font-size',SD.view.util.Contstant.articleFontSize);
            }
        }else{
           headerPage.setStyle('font-size',updatedHeaderFontSize);
           articlePage.setStyle('font-size',updatedArticleFontSize);
        }
    }

});
