/*
 * File: app/view/ContentPanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.ContentPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.contentpanel',

    requires: [
        'SD.view.ContentPanelViewModel',
        'Ext.panel.Tool'
    ],

    viewModel: {
        type: 'contentpanel'
    },
    id: 'content-pnl',
    itemId: 'contentPanel',
    scrollable: true,
    layout: 'fit',
    title: '',

    tools: [
        {
            xtype: 'tool',
            tooltip: 'Reduce font size',
            type: 'minus'
        },
        {
            xtype: 'tool',
            tooltip: 'Increase font size',
            type: 'plus'
        }
    ]

});