/*
 * File: app/view/MyContainerViewController.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.MyContainerViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.mycontainer',

    handleTreePanelResponsiveness: function(widthValue) {
         var minViewportWidth = SD.view.util.Contstant.minWidthValue;
                        var minimizeMenu = widthValue < minViewportWidth,
                                 naviPanel = Ext.ComponentQuery.query('#breadcrumb')[0],
                                 naviMinimizedMenu = Ext.ComponentQuery.query('#menuPanel')[0],
                                 fstool = Ext.ComponentQuery.query('#fullScreenId')[0];

                        if (minimizeMenu) {

                            fstool.setHidden(false);
                            naviPanel.show();
                            naviMinimizedMenu.hide();
                        }
                        else {
                            fstool.setHidden(true);
                            naviMinimizedMenu.show();
                            naviPanel.hide();
                        }
    },

    onHeaderPanelResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        this.handleTreePanelResponsiveness(width);
    }

});
