/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.MyContainer', {
    extend: 'Ext.container.Container',
    alias: 'widget.mycontainer',

    requires: [
        'SD.view.MyContainerViewModel',
        'SD.view.MyContainerViewController',
        'SD.view.TreePanel',
        'SD.view.ContentPanel',
        'Ext.tree.Panel'
    ],

    controller: 'mycontainer',
    viewModel: {
        type: 'mycontainer'
    },
    itemId: 'headerPanel',
    layout: 'border',

    items: [
        {
            xtype: 'treepanel',
            region: 'west',
            split: true
        },
        {
            xtype: 'contentpanel',
            region: 'center'
        }
    ],
    listeners: {
        resize: 'onHeaderPanelResize'
    },

    initComponent: function(config) {

        this.callParent();
        Ext.getBody().mask('Launching Slidedeck ...');
    }

});