/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.MyViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.myviewport',

    requires: [
        'SD.view.MyViewportViewModel',
        'SD.view.TreePanel',
        'SD.view.ContentPanel',
        'Ext.tree.Panel'
    ],

    viewModel: {
        type: 'myviewport'
    },
    itemId: 'headerPanel',
    layout: 'border',

    items: [
        {
            xtype: 'treepanel',
            region: 'west',
            split: true
        },
        {
            xtype: 'contentpanel',
            region: 'center'
        }
    ]

});