/*
 * File: app/view/TreePanel.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.TreePanel', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.treepanel',

    requires: [
        'SD.view.TreePanelViewModel',
        'SD.view.TreePanelViewController',
        'SD.view.override.TreePanel',
        'Ext.tree.View'
    ],

    controller: 'treepanel',
    viewModel: {
        type: 'treepanel'
    },
    itemId: 'menuPanel',
    width: 360,
    title: 'Panel',
    store: 'MenuStore',

    viewConfig: {
        itemId: 'treeMenu',
        listeners: {
            beforerender: 'onTreeMenuBeforeRender',
            itemclick: 'onTreeLeafItemClick'
        }
    }

});