/*
 * File: app/view/util/StringCleaner.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SD.view.util.StringCleaner', {
    extend: 'Ext.Base',

    singleton: true,

    rules: [
        'replaceHyphenWithSpace',
        'removeDotMD'
    ],

    replaceHyphenWithSpace: function(str) {
        return str.replace(/-/g, " ");
    },

    removeDotMD: function(str) {
        return str.replace('.md', "");
    },

    cleanup: function(str) {
        var me = this;
        var r = me.rules, l = me.rules.length;
        var retStr = str;

        for (var i = 0; i < l; i++) {
            retStr = me[r[i]](retStr);
        }

        return retStr;
    }

});